name: buildAndPublish

on:
  push:
    branches: ["master"]
    paths:
      - "src/**"
    tags:
      - v*.*.*
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install dependencies and build package
        run: |
          npm install -g tfx-cli typescript@4.6.3
          npm install
          npm run build
        working-directory: src/ConfigTransformTask
      - name: Build VSIX
        run: tfx extension create --manifest-globs vss-extension.json
        working-directory: src
      - name: Publish artifact
        if: ${{ github.event_name != 'pull_request'}}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: src/*.vsix
          include-hidden-files: true

  publish:
    name: Publish
    needs: build
    if: ${{ github.event_name != 'pull_request' &&  startsWith(github.ref, 'refs/tags/')}}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: output
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install tfx-cli
        run: |
          npm install -g tfx-cli
      - name: Publish to marketplace
        if: ${{ github.event_name != 'pull_request'}}
        run: tfx extension publish --token ${{ secrets.PUBLISH_TOKEN }} --service-url https://marketplace.visualstudio.com --vsix *.vsix
        working-directory: output
